spring:
  profiles:
    active: b
    include: c
  output:
    ansi:
      enabled: NEVER
  sql:
    init:
      schema-locations: classpath:db/schema.sql
c: 111

logging:
  config: classpath:log4j2.xml

d: application